version: "3.8"

services:
  api:
    build: ./app
    container_name: django_app
    command: gunicorn stocks_products.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    depends_on:
      - api
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  db_data:
